let stringMajors = [
  "Agroecology",
  "Anthropology",
  "Applied Linguistics and Multilingualism",
  "Applied Mathematics",
  "Applied Physics",
  "Art and Design: Games and Playable Media",
  "Art",
  "Biochemistry and Molecular Biology",
  "Biology (B.A.)",
  "Biology (B.S.)",
  "Biomolecular Engineering and Bioinformatics",
  "Biotechnology",
  "Business Management Economics",
  "Chemistry (B.A.)",
  "Chemistry (B.S.)",
  "Classical Studies",
  "Cognitive Science",
  "Community Studies",
  "Computer Engineering",
  "Computer Science (B.A.)",
  "Computer Science (B.S.)",
  "Computer Science: Computer Game Design",
  "Critical Race and Ethnic Studies",
  "Earth Sciences",
  "Earth Sciences/Anthropology Combined Major",
  "Ecology and Evolution",
  "Economics",
  "Economics/Mathematics Combined",
  "Education, Democracy, and Justice",
  "Electrical Engineering",
  "Environmental Sciences (B.S.)",
  "Environmental Studies (B.A.)",
  "Environmental Studies/Biology Combined Major",
  "Environmental Studies/Earth Sciences Combined Major",
  "Environmental Studies/Economics Combined Major",
  "Feminist Studies",
  "Film and Digital Media",
  "Global Economics",
  "History",
  "History of Art and Visual Culture",
  "Human Biology",
  "Jewish Studies",
  "Language Studies",
  "Latin American and Latino Studies",
  "Latin American and Latino Studies/Politics Combined",
  "Latin American and Latino Studies/Sociology Combined",
  "Legal Studies",
  "Linguistics",
  "Literature",
  "Marine Biology",
  "Mathematics (B.A.)",
  "Mathematics (B.S.)",
  "Mathematics Education",
  "Molecular, Cell, and Developmental Biology",
  "Music (B.A.)",
  "Music (B.M.)",
  "Network and Digital Technology",
  "Neuroscience",
  "Philosophy",
  "Physics (Astrophysics)",
  "Physics",
  "Plant Sciences",
  "Politics",
  "Psychology",
  "Robotics Engineering",
  "Science Education",
  "Sociology",
  "Spanish Studies",
  "Technology and Information Management",
  "Theater Arts",
];

const MAJORS = stringMajors.map(function (major) {
  return { label: major };
});
